name: Documentation
on:
  push:
    branches: ['main', 'v*']
    paths: ['./packages/**/src/**']
    tags: ['**']
jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    if: github.repository_owner == 'FalloutStudios'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref || '' }}
      - name: Install node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencidocses
        run: npm run bootstrap
      - name: Upload docgen artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docgen
          path: packages/*/docs/docs.json
