name: Documentation
on:
  push:
    branches: ['main', 'v7']
    # paths: ['./packages/*/src/**']
    tags: ['*']
  workflow_dispatch:
    inputs:
      ref:
        description: 'The branch, tag or SHA to checkout'
        required: true
      ref_type:
        type: choice
        description: 'Branch or tag'
        options:
          - branch
          - tag
        required: true
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    if: github.repository_owner == 'FalloutStudios'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref || '' }}

      - name: Install node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm run bootstrap

      - name: Build docs.json
        run: npm run docs

      - name: Upload docgen artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docgen
          path: packages/*/docs/docs.json
  upload:
    name: Upload Documentation
    needs: build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        package: ['reciple', 'client']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref || '' }}

      - name: Install node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Download docgen artifacts
        uses: actions/download-artifact@v3
        with:
          name: docgen
          path: docs

      - name: Checkout docs repository
        uses: actions/checkout@v3
        with:
          repository: 'FalloutStudios/Reciple'
          ref: 'docs'
          path: 'out'

      - name: Install dependencies
        run: npm run bootstrap

      - name: Parse package semver
        id: parse-semver
        uses: ./packages/actions/src/getSemver
        with:
          package: ${{ matrix.package }}

      - name: Move docs to correct directory
        if: ${{ matrix.package == steps.parse-semver.outputs.package }}
        env:
          PACKAGE: ${{ steps.parse-semver.outputs.package }}
          SEMVER: ${{ steps.parse-semver.outputs.semver }}
        run: |
          echo "docs/packages/${PACKAGE}/docs/docs.json > out/${PACKAGE}/${SEMVER}.json"
          mkdir -p out/${PACKAGE}
          mv docs/packages/${PACKAGE}/docs/docs.json out/${PACKAGE}/${SEMVER}.json

      - name: Commit and push
        run: |
          cd out
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Docs build for ${GITHUB_REF_TYPE} ${GITHUB_REF_NAME}: ${GITHUB_SHA}" || true
          git push
