name: Github Release
on:
  push:
    branches: ['main']
    tags: ['*reciple@*', '@reciple/*@*']
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    steps:
     - name: Checkout
       uses: actions/checkout@v3
     - name: Release
       uses: softprops/action-gh-release@v1
       if: ${{ !contains(github.ref_name, '-dev.') }}
       with:
        generate_release_notes: true
     - name: Pre-release
       uses: softprops/action-gh-release@v1
       if: ${{ contains(github.ref_name, '-dev.') }}
       with:
         prerelease: true
         generate_release_notes: true
